
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/balikesoftservices_db
    username: root
    password: Pvi@2021

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # Specify the MySQL dialect
        format_sql: true # Enable SQL formatting